# ==========================================
# Configuración de Conexión a MS SQL Server
# ==========================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EMPLOYEE_DIRECTORY;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=FYLQyuxzcT40TJoC
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver