# Use wildcard "*" to include all actuator endpoints
# Can also expose individual endpoints with a comma-separated list, e.g. "health,info"
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# Exclude individual endpoints with a comma-separated list, e.g. "health,info"
# management.endpoints.web.exposure.exclude=health,info

info.app.name=Spring Boot Actuator Demo
info.app.description=This is a demo application to show how to use Spring Boot Actuator.
info.app.version=1.0.0

#
# Define Custom Properties
#

coach.name=John Doe
team.name=Spring Boot Team