# Use wildcard "*" to include all actuator endpoints
# Can also expose indiviadual endpoints with a comma-separated list, e.g. "health,info"
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=Spring Boot Actuator Demo
info.app.description=This is a demo application to show how to use Spring Boot Actuator.
info.app.version=1.0.0