spring.application.name=thymeleafdemo

#-------------------------------------------------
# List of countries to be used in the application.
#-------------------------------------------------
countries=Brazil,Argentina,Colombia,Peru,Chile
programmingLanguages=Java,Python,JavaScript,C#,Ruby
operatingSystems=Windows,MacOS,Linux,Android OS,iOS
